### ISSUE TITLE
1D example error

### ISSUE THREAD

**Issue by mac-a** [tianyikillua/ddtruss#1]
Changing the 1D example in examples/truss.ipynb as
`points = np.array([
    [0, 0],
    [0.5, 0],
    [1, 0],
])
lines = np.array([
    [0, 1],
    [1, 2]
], dtype=int)
truss = Truss(points, lines)`

produces the following error

_---------------------------------------------------------------------------
AssertionError                            Traceback (most recent call last)
 in 
     47     idx=[0],
     48     n_neighbors=2,
---> 49     save_history=True,
     50 )
     51 

~/opt/anaconda3/lib/python3.7/site-packages/ddtruss/solver.py in solve(self, A, U_dict, F_dict, n_iterations, E_num, n_neighbors, idx, save_history)
    102                 construct_K = False
    103             u, eps, _ = self.truss.solve(
--> 104                 A=A, E=E_num, U_dict=U_dict, sig0=sig0, construct_K=construct_K
    105             )
    106 

~/opt/anaconda3/lib/python3.7/site-packages/ddtruss/truss.py in solve(self, A, E, U_dict, F_dict, sig0, construct_K)
     98 
     99         # Right hand side
--> 100         self._construct_F(F_dict, sig0)
    101         self._apply_Dirichlet(U_dict, F=self.F)
    102 

~/opt/anaconda3/lib/python3.7/site-packages/ddtruss/truss.py in _construct_F(self, F_dict, sig0)
    155         # Initial stress
    156         if sig0 is not None:
--> 157             assert len(sig0) == self.n_lines
    158             self._compute_elementary_quantities()
    159             for i, line in enumerate(self.lines):

AssertionError:_

**Comment by tianyikillua** [comment]
Well...actually the geometrically linear 2-d truss with
```
points = np.array([ [0, 0], [0.5, 0], [1, 0], ])
lines = np.array([ [0, 1], [1, 2] ], dtype=int)
```
is not actually a *structure* but a *mechanism*...It is not stable at the central point.

**Comment by mac-a** [comment]
> Well...actually the geometrically linear 2-d truss with
> 
> ```
> points = np.array([ [0, 0], [0.5, 0], [1, 0], ])
> lines = np.array([ [0, 1], [1, 2] ], dtype=int)
> ```
> 
> is not actually a _structure_ but a _mechanism_...It is not stable at the central point.

aaah! structures 101. thanks a lot
